global:
  infraId: "1234"
  accessKey: "xyz"
  accountId: "abcd"
  workflowInstanceId: "6789"

subscriber:
  image:
    registry: docker.io
    repository: chaosnative/harness-chaos-subscriber
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.23.0"

  upgrader:
    image:
      registry: docker.io
      repository: chaosnative/harness-k8s-chaos-infrastructure-upgrader
      pullPolicy: Always
      # Overrides the image tag whose default is the chart appVersion.
      tag: "1.23.0"


  version: 1.23.0

  skipSslVerify: "false"

  connectionType: HTTPS

  isSecretEnabled: "true"


  serviceAccount: 
    name: hce

  securityContext:
    runAsUser: 2000
    runAsGroup: 2000
    allowPrivilegeEscalation: false

  resources:
    requests:
      memory: "300Mi"
      cpu: "125m"
      ephemeral-storage: "500Mi"
    limits:
      memory: "500Mi"
      cpu: "225m"
      ephemeral-storage: "1Gi"

workflow-controller:
  image:
    registry: docker.io
    repository: chaosnative/workflow-controller
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v3.4.10"

  argoExec:
    image:
      registry: docker.io
      repository: chaosnative/argoexec
      pullPolicy: Always
      # Overrides the image tag whose default is the chart appVersion.
      tag: "v3.4.10"

  serviceAccount: 
    name: hce

  securityContext:
    runAsUser: 2000
    runAsGroup: 2000
    allowPrivilegeEscalation: false

  resources:
    requests:
      memory: "300Mi"
      cpu: "125m"
      ephemeral-storage: "500Mi"
    limits:
      memory: "500Mi"
      cpu: "225m"
      ephemeral-storage: "1Gi"
chaos-operator:
  image:
    registry: docker.io
    repository: chaosnative/chaos-operator
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.23.1"

  chaosRunner:
    image:
      registry: docker.io
      repository: chaosnative/chaos-runner
      pullPolicy: Always
      # Overrides the image tag whose default is the chart appVersion.
      tag: "1.23.0"

  serviceAccount: 
    name: hce

  securityContext:
    runAsUser: 2000
    runAsGroup: 2000
    allowPrivilegeEscalation: false

  resources:
    requests:
      memory: "300Mi"
      cpu: "125m"
      ephemeral-storage: "500Mi"
    limits:
      memory: "500Mi"
      cpu: "225m"
      ephemeral-storage: "1Gi"
chaos-exporter:
  image:
    registry: docker.io
    repository: chaosnative/chaos-exporter
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.23.0"

  serviceAccount: 
    name: hce

  securityContext:
    runAsUser: 2000
    runAsGroup: 2000
    allowPrivilegeEscalation: false

  resources:
    requests:
      memory: "300Mi"
      cpu: "125m"
      ephemeral-storage: "500Mi"
    limits:
      memory: "500Mi"
      cpu: "225m"
      ephemeral-storage: "1Gi"


