global:
  infraId: "1234"
  accessKey: "xyz"
  #accountId: "abcd"
  workflowInstanceId: "6789"
  
subscriber:
  image:
    registry: docker.io
    repository: harness/chaos-subscriber
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.38.1"

  upgrader:
    image:
      registry: docker.io
      repository: harness/k8s-chaos-infrastructure-upgrader
      pullPolicy: Always
      # Overrides the image tag whose default is the chart appVersion.
      tag: "1.38.0"

  customTlsCert: ""
  version: 1.38.0

  skipSslVerify: "false"

  connectionType: HTTPS

  isSecretEnabled: "true"

  serviceAccount: 
    name: hce

  securityContext:
    runAsUser: 2000
    runAsGroup: 2000
    allowPrivilegeEscalation: false

  resources:
    requests:
      memory: "300Mi"
      cpu: "125m"
      ephemeral-storage: "500Mi"
    limits:
      memory: "500Mi"
      cpu: "225m"
      ephemeral-storage: "1Gi"
  nodeSelector: {}
  affinity: {}
  tolerations: []

workflow-controller:
  image:
    registry: docker.io
    repository: harness/chaos-workflow-controller
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v3.4.16"

  argoExec:
    image:
      registry: docker.io
      repository: harness/chaos-argoexec
      pullPolicy: Always
      # Overrides the image tag whose default is the chart appVersion.
      tag: "v3.4.16"

  serviceAccount: 
    name: hce

  securityContext:
    runAsUser: 2000
    runAsGroup: 2000
    allowPrivilegeEscalation: false

  resources:
    requests:
      memory: "300Mi"
      cpu: "125m"
      ephemeral-storage: "500Mi"
    limits:
      memory: "500Mi"
      cpu: "225m"
      ephemeral-storage: "1Gi"
  nodeSelector: {}
  affinity: {}
  tolerations: []
chaos-operator:
  image:
    registry: docker.io
    repository: harness/chaos-operator
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.38.0"

  chaosRunner:
    image:
      registry: docker.io
      repository: harness/chaos-runner
      pullPolicy: Always
      # Overrides the image tag whose default is the chart appVersion.
      tag: "1.38.1"

  serviceAccount: 
    name: hce

  securityContext:
    runAsUser: 2000
    runAsGroup: 2000
    allowPrivilegeEscalation: false

  resources:
    requests:
      memory: "300Mi"
      cpu: "125m"
      ephemeral-storage: "500Mi"
    limits:
      memory: "500Mi"
      cpu: "225m"
      ephemeral-storage: "1Gi"
  nodeSelector: {}
  affinity: {}
  tolerations: []
chaos-exporter:
  image:
    registry: docker.io
    repository: harness/chaos-exporter
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.38.0"

  serviceAccount: 
    name: hce

  securityContext:
    runAsUser: 2000
    runAsGroup: 2000
    allowPrivilegeEscalation: false

  resources:
    requests:
      memory: "300Mi"
      cpu: "125m"
      ephemeral-storage: "500Mi"
    limits:
      memory: "500Mi"
      cpu: "225m"
      ephemeral-storage: "1Gi"
  nodeSelector: {}
  affinity: {}
  tolerations: []




